version: '2'

networks:
  custom:

services:

  ca.org1.vancir.com:
    container_name: ca_peerOrg1
    image: hyperledger/fabric-ca:1.3.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org1.vancir.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/1e3e3389a3c5a3e3dbda7f8a2bf190fcd40c681a8996fd0d15e1e74eb52924dc_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/ca:/etc/hyperledger/fabric-ca-server
    networks:
      - custom

  ca.org2.vancir.com:
    container_name: ca_peerOrg2
    image: hyperledger/fabric-ca:1.3.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org2.vancir.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/8bcb6d6f596e94feffe4286127ccfdd3048cf459e7ad908679ac10a13abc4898_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/ca:/etc/hyperledger/fabric-ca-server
    networks:
      - custom

  orderer.vancir.com:
    container_name: orderer.vancir.com
    image: hyperledger/fabric-orderer:1.3.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    networks:
      - custom
    ports:
      - 7050:7050
    volumes:
      - ../network-resources/channel-artifacts:/etc/hyperledger/channel-artifacts
      - ../network-resources/crypto-config/ordererOrganizations/vancir.com/orderers/orderer.vancir.com:/etc/hyperledger/msp/orderer
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/peers/peer0.org1.vancir.com:/etc/hyperledger/msp/peerOrg1
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/peers/peer0.org2.vancir.com:/etc/hyperledger/msp/peerOrg2

  peer0.org1.vancir.com:
    container_name: peer0.org1.vancir.com
    image: hyperledger/fabric-peer:1.3.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.vancir.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.org1.vancir.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - custom
    volumes:
      - /var/run/:/host/var/run/
      - ../network-resources/channel-artifacts:/etc/hyperledger/channel-artifacts
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/peers/peer0.org1.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com

  peer1.org1.vancir.com:
    container_name: peer1.org1.vancir.com
    image: hyperledger/fabric-peer:1.3.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.vancir.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.org1.vancir.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - custom
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
      - /var/run/:/host/var/run/
      - ../network-resources/channel-artifacts:/etc/hyperledger/channel-artifacts
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/peers/peer1.org1.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com

  peer0.org2.vancir.com:
    container_name: peer0.org2.vancir.com
    image: hyperledger/fabric-peer:1.3.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.vancir.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.org2.vancir.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - custom
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ../network-resources/channel-artifacts:/etc/hyperledger/channel-artifacts
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/peers/peer0.org2.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com

  peer1.org2.vancir.com:
    container_name: peer1.org2.vancir.com
    image: hyperledger/fabric-peer:1.3.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.vancir.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.org2.vancir.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_custom
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - custom
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
      - /var/run/:/host/var/run/
      - ../network-resources/channel-artifacts:/etc/hyperledger/channel-artifacts
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/peers/peer1.org2.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com
