version: '2'

services:

  ca.org1.vancir.com:
    container_name: ca_peerOrg1
    extends: 
      file: common-services.yml
      service: ca
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org1.vancir.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/9266f71d859583c78a560830cddde31cc5f417a0c8e7e6242970804317dadb40_sk
    ports:
      - "7054:7054"
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/ca:/etc/hyperledger/fabric-ca-server

  ca.org2.vancir.com:
    container_name: ca_peerOrg2
    extends:
      file: common-services.yml
      service: ca
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org2.vancir.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/9f61e2173cba927421ee0998680940fac2e08d82cbf6c8e226e3d241b52d6832_sk
    ports:
      - "8054:7054"
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/ca:/etc/hyperledger/fabric-ca-server

  orderer.vancir.com:
    container_name: orderer.vancir.com
    extends:
      file: common-services.yml
      service: orderer
    environment:
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    ports:
      - 7050:7050
    volumes:
      - ../network-resources/crypto-config/ordererOrganizations/vancir.com/orderers/orderer.vancir.com:/etc/hyperledger/msp/orderer
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/peers/peer0.org1.vancir.com:/etc/hyperledger/msp/peerOrg1
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/peers/peer0.org2.vancir.com:/etc/hyperledger/msp/peerOrg2

  peer0.org1.vancir.com:
    container_name: peer0.org1.vancir.com
    extends:
      file: common-services.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.org1.vancir.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.vancir.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.vancir.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/peers/peer0.org1.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com

  peer1.org1.vancir.com:
    container_name: peer1.org1.vancir.com
    extends:
      file: common-services.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.org1.vancir.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.vancir.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.vancir.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/peers/peer1.org1.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org1.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com

  peer0.org2.vancir.com:
    container_name: peer0.org2.vancir.com
    extends:
      file: common-services.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.org2.vancir.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.vancir.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.vancir.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/peers/peer0.org2.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com

  peer1.org2.vancir.com:
    container_name: peer1.org2.vancir.com
    extends:
      file: common-services.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.org2.vancir.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.vancir.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.vancir.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/peers/peer1.org2.vancir.com/msp:/etc/hyperledger/fabric/msp
      - ../network-resources/crypto-config/peerOrganizations/org2.vancir.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.vancir.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.3.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.vancir.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.vancir.com/peers/peer0.org1.vancir.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.vancir.com/peers/peer0.org1.vancir.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.vancir.com/peers/peer0.org1.vancir.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.vancir.com/users/Admin@org1.vancir.com/msp
    working_dir: /opt/gopath/src/github.com/
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../network-resources/chaincode/:/opt/gopath/src/github.com/chaincode
        - ../network-resources/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../network-resources/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.vancir.com
      - peer0.org1.vancir.com
      - peer1.org1.vancir.com
      - peer0.org2.vancir.com
      - peer1.org2.vancir.com
  
  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.org1.vancir.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.vancir.com/users/Admin@org1.vancir.com/msp
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.vancir.com/users/Admin@org1.vancir.com/tls/client.crt
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.vancir.com/users/Admin@org1.vancir.com/tls/client.key
    working_dir: /opt/gopath/src/github.com/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
        - /var/run/:/host/var/run/
        - ../network-resources/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../network-resources/chaincode/:/opt/gopath/src/github.com/chaincode
    depends_on:
      - orderer.vancir.com
      - peer0.org1.vancir.com
      - peer1.org1.vancir.com
      - peer0.org2.vancir.com
      - peer1.org2.vancir.com